### PR TITLE
Drental pf2e 2.4 fixes

### PR DESCRIPTION
**Pull request by Drental**
this one also implements Supe's fix

### CODE REVIEW

**Comment by Drental** [comment]
But it also removes the old NPC strikes (their last useful feature got absorbed into the new strikes recently) and cleans up a few options.

I'll go through some more bits later, but it's 5am

**Comment by Drental** [comment]
(this state works and doesn't spam the console on 0.8 anymore)

**Comment by CarlosFdez** [comment]
There's a components getter that simplifies the components population, which is what I used in my PR. But you can do this as well.

**Comment by espositos** [comment]
Thanks a lot, both of you

**Pull request merged**
